@startuml
start
:Open user button on navbar;
:Click on "Thay đổi mật khẩu" button;
:Redirect to change password page;
:Input old password, new password and confirmed password;
if (Change Password successully?) then (success)
    :Redirect to homepage;
    :Show success toast message;
else (fail)
    :Redirect to homepage;
    :Show error toast message;
endif
stop
@enduml
