@startuml
start
:Click on a specific conversation;
if (get success) then (success)
    :Return response;
    :Redirect to conversation details page;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml
