@startuml
start
:Click on the bell button on navbar;
:A pop-up is displayed;
:Click on "Xem tất cả" text;
:Redirect to notification page;
if (Has notification?) then (yes)
    :Return response;
    :Show all of the noitfications;
else (no)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml
