@startuml
start
:Open task page;
:Click on a specific task;
:A pop-up will be displayed;
:Click on status which want to update at "Trạng thái" section;
if (Update success?) then (success)
    :Return response;
    :Redirect to event detail page with the new task which is updated;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml
