@startuml
actor Employee as user
participant Browser as a
participant AuthController as b
participant AuthService as c
participant UserService as d
participant UserRepository as e
database Database as f

user -> a: Click "Đổi mật khẩu" button
a -> b++: Send a request
b -> c++: Call changePassword()
c -> d++: Call findByEmail()
d -> e++: Call findByEmail()
e -> f++: Query
f --> e: Return result
alt User is not null
    e --> d: Return user
    d -> e: Call updatePassword()
    e -> f: Query
    f --> e--: Return result
    alt Success
        e --> d: Return true
        d --> c: Return true
        c --> b: Return true
        b --> a: Return success response
        a --> user: Display message "Thay đổi mật khẩu thành công"
    else Fail 
        e --> d: Return false
        d --> c: Return false
        c --> b: Return false
        b --> a: Return fail response
        a --> user: Display message "Thay đổi mật khẩu thất bại"
    end  
else User is null
    e --> d--: Return null
    d --> c--: Return null
    c --> b--: Return null
    b --> a--: Return fail response
    a --> user: Display error message "Không thể tìm thấy người dùng này"
end
@enduml