@startuml
actor Employee as user
participant Browser as a
participant "Comment Controller" as b
participant "Comment Service" as c
participant "Task Service" as d
participant "Comment Repository" as e
database Database as f

user -> a++: Fill the bank at comment text input of a specific task
a -> b++: POST: /comment
b -> c++: call createComment()
c -> d++: call findUserInTask()
d -> f++: Query
alt User in task
    f --> d--: Return result
    d -> e++: call save()
    e -> f++: Create
    alt Success
        f --> e: Return result
        e --> d: Return response
        d --> c: Return response
        c --> b: Return response
        b --> a: Return response
        a --> user: Display message "Bình luận thành công"
    else Fail
         f --> e: Return null
         e --> d: Return response
         d --> c: Return response
         c --> b: Return response
         b --> a: Return response
         a --> user: Display message "Bình luận thất bại"
    end
else User doesn't in task
    f --> e--: Return null
    e --> d--: Return response
    d --> c--: Return response
    c --> b--: Return response
    b --> a--: Return response
    a --> user--: Display error message "Bạn không có quyền được bình luận trong công việc này"
end
@enduml