@startuml
start
:Click on specific task;
:A pop-up task detail will be displayed
:Click to choose person at "Người tham gia" section;
if (update success) then (success)
    :Return response;
    :Redirect to task page;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml
