@startuml
start
:Click on "Nhân sự" tab on navbar;
:"Nhân sự" page is displayed;
:Click on "Thêm mới" button;
:Input the information to create;
:Click on "Tạo" button;
if (create success?) then (success)
    :Return response;
    :Redirect to "Nhân sự" page;
else (fail)
    :Return error response;
    :Show error message from server in toast message;
endif
stop
@enduml
