@startuml
start
:Click on a specific task;
:A pop-up will be displayed;
:Input comment at text field comment section;
:Press enter on keyboard or click on "Send" icon;
if (Create success?) then (success)
    :Return response;
    :New comment will be displayed at task's popup;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml