@startuml
start
:Click on "Thêm mới công việc" at a specìic event;
:Input the information to create;
:Click on "Tạo" button;
if (Create success?) then (success)
    :Return response;
    :Redirect to event detail page with the new task which is created;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml
