@startuml
start
:Click on "Yêu cầu" tab in Ngân sách page;
if (get success?) then (success)
    :Return response;
    :Redirect to "Yêu cầu" page;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml