@startuml
start
:Click on "Sự kiện" tab on navbar;
if (get success?) then (success)
    :Return response;
    :Redirect to "Sự kiện" page;
else (fail)
    :Return error response;
    :Show error message from server in toast message;
endif
stop
@enduml
