@startuml
start
:Click on user icon button at navbar;
if (get success) then (success)
    :Return response;
    :Redirect to user profile details;
else (fail)
     :Return error response;
     :Show error message from server in a toast message;
endif
stop
@enduml
