@startuml
start
:Click on "..." icon of a specific comment;
:A option list will be displayed;
:Click on "Chỉnh sửa" button;
:Input the new content;
:Click on "Cập nhật" button;
if (Delete success?) then (success)
    :Return response;
    :Redirect to task details page;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml