@startuml
start
:Open task page;
:Click on a specific task;
:Input the information to update;
if (Update success?) then (success)
    :Return response;
    :Redirect to event detail page with the new task which is updated;
else (fail)
    :Return error response;
    :Show error message from server in a toast message;
endif
stop
@enduml
