@startuml

actor Manager as user
participant Browser as a
participant "Notification Controller" as b
participant "Notification Service" as c
participant "User Notification Service" as d
participant "Notification Repository" as e
database Database as f

user -> a++: Click on the bell icon
a -> b++: GET: /notification
b -> c++: call getMyNotifications()
c -> d++: call getMyNotifications()
d -> e++: call findAll()
e -> f++: Query
f --> e--: Return results
e --> d--: Return response
d --> c--: Return response
c --> b--: Return response
b --> a--: Return response
a --> user--: Display all of the notifications
@enduml