@startuml

actor Guest as Guest

participant ":Browser" as a
participant ":AuthController" as b
participant ":AuthService" as c
participant ":UserService" as d
participant ":MailService" as e
database ":Database" as f

Guest -> a: 1. Click "Quên mật khẩu" button
a -> b++ : 2. Send a request
b -> c++: 3. Call forgetPassword()
c -> d++: 3. Call findUserByEmail()
d -> f++: 4. Query
f --> d: 5. Return result
alt User is not null
    d -> e++: 6.1 Call sendMail()
    e -> e: 7.1 Send mail
    e --> d: 8.1 Return result
    d --> c: 9.1. Return result
    c --> b: 10.1 Return result
    b --> a: 11.1 Return success response
    alt Success
        Guest -> a: 12. Input verification code
        a -> b++: 13. Send a request
        b -> c++: 14. Call verifyCode()
        
    else Fail
    end
else User is null
    d --> c: 6.2 Return result
    c --> b: 7.2 Return result
    b --> a: 8.2 Return fail response
    
end
@enduml