@startuml
actor Customer as A
participant ":Browser" as B
participant ":Contract Controller" as C
participant ":Contract Service" as D
participant ":Contract Repository" as E
database ":Database" as F

A -> B++: Click on a specific contract was created
B -> C++: GET: /contracts/file/customer
C -> D++: call getAllContractFileByCustomer()
D -> E++: call find()
E -> F++: Query
F --> E--: Return result
E --> D--: Return response
D --> C--: Return response
C --> B--: Return response
B --> A--: Display the result
@enduml