@startuml
actor Manager as user
participant ":Browser" as a
participant ":Event Controller" as b
participant ":Event Service" as c
participant ":Event Repository" as d
participant ":Database" as e

user -> a++: Click on "Sự kiện" tab
a -> b++: GET: /event/filter
b -> c++: call filterEventByCondition()
c -> d++: call find()
d -> e++: Query
e --> d--: Return result
d --> c--: Return response
c --> b--: Return response
b --> a--: Return response
a --> user--: Display all of the event's information
@enduml