@startuml

actor "Unauthenticated User" as Guest

participant Browser as a
participant AuthController as b
participant AuthService as c
participant UserService as d
participant MailService as e
database Database as f

Guest -> a++: Click "Quên mật khẩu" button
a -> b++ : Send a request
b -> c++: Call forgetPassword()
c -> d++: Call findUserByEmail()
d -> f++: Query
f --> d: Return result
alt User is not null
    d -> e++:  Call sendMail()
    e -> e: Send mail
    e --> d--: Return result
    d --> c: Return result
    c --> b: Return result
    b --> a: Return success response
    Guest -> a: Input verification code
    a -> b: Send a request
    b -> c: Call verifyCode()
    c -> f: Query
    alt Verification Success
    f --> c: Return result
    c --> b: Return response;
    b --> a: Return response;
    a --> Guest: Return success response     
    Guest -> a: Input new password
    a -> b: Send a request
    b -> c: call updatePassword()
    c -> f: UPDATE
    alt Success
    f --> c: Return result
    c --> b: Return response;
    b --> a: Return response;
    a --> Guest: Return success response
    else Fail
    f --> c: Return result
    c --> b: Return response;
    b --> a: Return response;
    a --> Guest: Return fail response
    end    
    else Verification Fail
    f --> c--: Return result
    c --> b: Return response;
    b --> a: Return response;
    a --> Guest: Return fail response
    end
else User is null
    d --> c--: Return result
    c --> b--: Return result
    b --> a--: Return fail response
    a --> Guest--: Display error response
end
@enduml