export const AUTH_ERROR_MESSAGE = {
  USER_NOT_EXIST: 'USER_NOT_EXIST',
  EMAIL_EXIST: 'EMAIL_EXIST',
  USER_NOT_VERIFY: 'USER_NOT_VERIFY',
};

export const USER_ERROR_MESSAGE = {
  USER_NOT_EXIST: 'USER_NOT_EXIST',
  EMAIL_EXIST: 'EMAIL_EXIST',
  CANT_CHANGE: 'CANT_CHANGE',
};

export const DIVISION_ERROR_MESSAGE = {
  DIVISION_NOT_EXIST: 'DIVISION_NOT_EXIST',
  CANT_CHANGE: 'CANT_CHANGE_STATUS',
};
