export const AUTH_ERROR_MESSAGE = {
  USER_NOT_EXIST: 'USER_NOT_EXIST',
  EMAIL_EXIST: 'EMAIL_EXIST',
  USER_NOT_VERIFY: 'USER_NOT_VERIFY',
};

export const USER_ERROR_MESSAGE = {
  USER_NOT_EXIST: 'USER_NOT_EXIST',
  EMAIL_EXIST: 'EMAIL_EXIST',
  CANT_CHANGE: 'CANT_CHANGE',
};

export const DIVISION_ERROR_MESSAGE = {
  DIVISION_NOT_EXIST: 'DIVISION_NOT_EXIST',
  CANT_CHANGE: 'CANT_CHANGE_STATUS',
};

export const EVENT_ERROR_MESSAGE = {
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
};

export const ASSIGN_ERROR_MESSAGE = {
  NO_ASSIGNEE: 'NO_ASSIGNEE_SELECTED',
};

export const TASK_ERROR_MESSAGE = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
};
