@startuml
start
:Click on "Đội nhóm" tab on navbar;
if (get success) then (sucess)
    :Return response;
    :Redirect to "Đội nhóm" page;
else (fail)
    :Return error response;
    :Show error message from server in toast message;
endif
stop
@enduml