@startuml

actor Customer as A
participant ":Browser" as B
participant ":Customer Contact Controller" as C
participant ":Customer Contact Service" as D
participant ":Customer Contact Repository" as E
database ":Database" as F

A -> B: Click on "Cập nhật" of a specific contact
activate B
B -> C: PUT /:id
activate C
C -> D: call updateContact()
activate D
D -> E: call update()
activate E
E -> F: Update
activate F
    F --> E: Return data
deactivate F
    E --> D: Return data
deactivate E
    D --> C: Return data
deactivate D
    C --> B: Return data
deactivate C
    B --> A: Display data information
deactivate B

@enduml