@startuml

actor Customer as A
participant ":Browser" as B
participant ":Customer Contact Controller" as C
participant ":Customer Contact Service" as D
participant ":Customer Contact Repository" as E
database ":Database" as F

A -> B++: Click on specific contact
B -> C++: GET /:id
C -> D++: call getContactDetailsById()
D -> E++: call findOne()
E -> F++: Query
alt Success
    F --> E: Return data
    E --> D: Return data
    D --> C: Return data
    C --> B: Return data
    B --> A: Display contact information
else Failure
    F --> E--: Return null
    E --> D--: Return null
    D --> C--: Return null
    C --> B--: Return error message "Không tìm thấy thông tin liên hệ này"
    B --> A--: Display error message "Không tìm thấy thông tin liên hệ này"
end

@enduml