@startuml

actor Customer as A
participant ":Browser" as B
participant ":Customer Contact Controller" as C
participant ":Customer Contact Service" as D
participant ":Customer Contact Repository" as E
database ":Database" as F

A -> B++: Click on "Danh sách liên hệ" button
B -> C++: GET /info
C -> D++: call leaveMessage()
D -> E++: call save()
E -> F++: save data


alt Success
    F --> E: Return data was stored
    E --> D: Return data was stored
    D --> C: "Leave message successfully"
    C --> B: "Leave message successfully"
    B --> A: "Tạo liên hệ thành công"
else Failure
    F --> E--: Return null
    E --> D--: Return null
    D --> C--: "Leave message fail"
    C --> B--: "Leave message fail"
    B --> A--: "Leave message fail"
end

@enduml