@startuml

actor Authenticated_User as user
participant Browser as a
participant AuthController as b
participant AuthService as c
participant UserService as d
participant UserRepository as e
database Database as f

user -> a: 1. Click "Đổi mật khẩu" button
a -> b++: 2. Send a request
b -> c++: 3. Call changePassword()
c -> d++: 4. Call findByEmail()
d -> e++: 5. Call findByEmail()
e -> f++: 6. Query
f --> e: 7. Return result
alt User is not null
    e --> d: 8.1. Return user
    d -> e: 9.1. Call updatePassword()
    e -> f: 10.1. Query
    f --> e--: 11.1. Return result
    alt Success
        e --> d: 12.1.1. Return true
        d --> c: 13.1.1. Return true
        c --> b: 14.1.1. Return true
        b --> a: 15.1.1. Return success response
    else Fail 
        e --> d: 12.1.2. Return false
        d --> c: 13.1.2. Return false
        c --> b: 14.1.2. Return false
        b --> a: 15.1.2. Return fail response
    end  
else User is null
    e --> d: 8.2. Return null
    d --> c: 9.2. Return null
    c --> b: 10.2. Return null
    b --> a: 11.2. Return fail response
end
@enduml