@startuml

actor Manager as manager

participant Browser as a 
participant EventController as b 
participant EventService as c 
participant EventRepository as d 
database Database as e 

manager -> a: 1. Click "Tạo mới" button
a -> b++: 2. Send a request 
b -> c++: 3. Call createEvent() 
c -> d++: 3. Call insertEvent()
d -> e++: 4. Insert 
e --> d--: 5. Return result 

alt Success
    d --> c: 6.1. Return true 
    c --> b: 7.1. Return true
    b --> a: 8.1. Return success response
else Fail
    d --> c: 6.2. Return false 
    c --> b: 7.2. Return false
    b --> a: 8.2. Return fail response
end 
@enduml