@startuml
autonumber
actor Unauthenticated as User
participant Browser as A
participant AuthController as B
participant AuthService as C
participant UserService as D
participant UserRepository as E
database Database

User -> A: Enter email and password
A -> B: POST /login
B -> C: call login() method
C -> D: call findUserByEmail() method
D -> E: call findUserByEmail() method
E -> Database: Query user
Database --> E: Retrive user
alt User not found
    E -> D: return null
    D -> C: return null
    C -> B: return null
    B -> A: return null
    A -> User: Show error message
else User found
    E -> D: return user
    D -> C: return user
    C -> C++: validate username and password
    B -> A: return user
end
@enduml