@startuml

actor Manager as user 

participant Browser as a
participant UserController as b 
participant UserService as c 
participant UserRepository as d 
database Database as e 

user -> a: 1. Click "Cập nhật" on specific user
a -> b++: 2. Send a request  
b -> c++: 3. Call updateProfile()
c -> d++: 4. Call updateProfile()
d -> e++: 5. Update
e --> d--: 6. Return result
alt Success
    d --> c: 7.1. Return true
    c --> b: 8.1. Return true
    b --> a: 9.1. Return success response
else Fail 
    d --> c: 7.2. Return false
    c --> b: 8.2. Return false
    b --> a: 9.2. Return fail response
end 
@enduml